import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types ../fibrie/src/lib/appwrite/database/ --language ts`.

export enum PatternDifficulty {
    BEGINNER = "beginner",
    INTERMEDIATE = "intermediate",
    ADVANCED = "advanced",
    EXPERT = "expert"
}

export enum PatternProjectType {
    KNITTING = "knitting",
    CROCHET = "crochet"
}

export enum PatternTranslationLocale {
    CS = "cs",
    DE = "de",
    EN = "en",
    ES = "es",
    FR = "fr",
    SK = "sk"
}

export enum AbbreviationCraft {
    KNITTING = "knitting",
    CROCHET = "crochet"
}

export enum AbbreviationTranslationLocale {
    CS = "cs",
    DE = "de",
    EN = "en",
    ES = "es",
    FR = "fr",
    SK = "sk"
}

export enum AbbreviationTranslationRegion {
    US = "us",
    UK = "uk",
    UNIVERSAL = "universal"
}

export type Pattern = Models.Row & {
    profile: Profile;
    difficulty: PatternDifficulty;
    translations: PatternTranslation[];
    project_type: PatternProjectType;
    images: string[] | null;
    estimated_minutes: number;
    pattern_rating: PatternRating;
}

export type Profile = Models.Row & {
    user_name: string;
    public_name: string | null;
}

export type PatternTranslation = Models.Row & {
    pattern: Pattern;
    locale: PatternTranslationLocale;
    title: string;
    description: string | null;
}

export type Abbreviation = Models.Row & {
    craft: AbbreviationCraft;
    icon_id: string;
    image_ids: string[] | null;
    video_urls: string[] | null;
    translations: AbbreviationTranslation[];
}

export type AbbreviationTranslation = Models.Row & {
    abbreviation: Abbreviation;
    locale: AbbreviationTranslationLocale;
    region: AbbreviationTranslationRegion;
    abbr: string;
    title: string;
    description: string | null;
}

export type PatternRating = Models.Row & {
    rating_1: number;
    rating_2: number;
    rating_3: number;
    rating_4: number;
    rating_5: number;
}

export type PatternReview = Models.Row & {
}
